### PR TITLE
Draft: Update and fix

### PR DESCRIPTION
**Pull request by stufisher**
Merges a variety of other peoples MRs:
* https://github.com/Villarrealized/sonos-web/pull/65
* https://github.com/Villarrealized/sonos-web/pull/61
* https://github.com/Villarrealized/sonos-web/pull/60

Fixed / added:
* Added ability to set spotify region from .env: `REGION=EU`
* Fix removing zone from groups
* Disable group volume and seek (event triggered loop)

Todo:
- [x] Cant load spotify playlists or albums (upnp error 500 => error code 804) => https://github.com/bencevans/node-sonos/pull/502
- [x] Cant load albums with artist != album artist => https://github.com/bencevans/node-sonos/pull/498
- [x] Cant load shared folder (upnp error 500) => https://github.com/bencevans/node-sonos/pull/499
- [x] Get aa for radio now playing => https://github.com/bencevans/node-sonos/pull/500

### CODE REVIEW

**Comment by Villarrealized** [comment]
@stufisher Thank you, for all your work here! Unfortunately, I haven't been able to devote any time to this project for a long time as everyone has likely noticed. 

Going to look over your changes and approve them shortly.

**Comment by stufisher** [comment]
Hey @Villarrealized, no worries. I forked your repo into an org here https://github.com/sonos-web/sonos-web with the changes merged into master, sorted out some ci, and auto docker images. I can add you there too if you like so we can have multiple people that can manage the repo?

Sorry for the multple prs against this repo, it pulls by default to the upstream fork, i meant to merge into the `sonos-web/sonos-web` repo!

**Comment by Villarrealized** [comment]
@stufisher That sounds like a good idea. Do you think it would be better if I transferred ownership to the org instead? We do have 184 stars on this repo and I'd hate to see all that visibility go away. Do you know if we can transfer and keep that?

**Comment by Villarrealized** [comment]
So, it won't let me transfer the repo, because the `sonos-web` org already has a repo called `sonos-web`

**Comment by stufisher** [comment]
Yes indeed, would be a shame to loose that, i'll try to rename in the org, then we can pull master from my fork into master here, transfer here back to the org, and i think we should be up to date? As long as the code looks ok from your side (i'm running the docker container here)

**Comment by stufisher** [comment]
Have renamed in the org so i think you should be able to transfer :)

**Comment by Villarrealized** [comment]
Here is the error now.

Screen Shot 2022-08-20 at 10 05 17 AM

**Comment by Villarrealized** [comment]
Maybe because you forked it from my repo, it won't allow the transfer? So, I'm assuming you would need to remove the fork from the org before we can transfer?

**Comment by stufisher** [comment]
I can get github to unlink my fork from yours, then i think you can transfer. I dont really want to delete it until everything is merged in. You have to make a manual request though

**Comment by Villarrealized** [comment]
Gotcha. Trying to see where I can do that...

**Comment by stufisher** [comment]
Ok i deleted in the org, i think you should be able to transfer

**Comment by Villarrealized** [comment]
Done

**Comment by stufisher** [comment]
Much appreciated! :)

**Comment by stufisher** [comment]
Is there any way to share the npm login details or send me a token? I'll try and sort out the ci release to push to npm too. Is there a way for us to chat no via comments? :)

https://docs.npmjs.com/creating-an-organization ? I can sign up on npm too

**Comment by Villarrealized** [comment]
Sure, we can chat via Slack. Here's an invite link: https://join.slack.com/t/slack-2f79017/shared_invite/zt-1eg88iaif-bUOi3wui2hluQpQslIt3DA

**Pull request merged**
